# Generated by Django 4.2.7 on 2023-11-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=35, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('pizza', 'pizza'), ('pasta', 'pasta'), ('Dinner Platters', 'Dinner PLatters')], max_length=15, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('tamano', models.CharField(blank=True, choices=[('SM', 'Small'), ('L', 'Large')], max_length=30, null=True)),
                ('toppings', models.CharField(blank=True, max_length=30, null=True)),
                ('cantidad_toppings', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
